package com.lesincs.simpleread.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lesincs.simpleread.bean.DBJDNews;
import com.lesincs.simpleread.bean.DBZHNews;

import com.lesincs.simpleread.dao.DBJDNewsDao;
import com.lesincs.simpleread.dao.DBZHNewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBJDNewsDaoConfig;
    private final DaoConfig dBZHNewsDaoConfig;

    private final DBJDNewsDao dBJDNewsDao;
    private final DBZHNewsDao dBZHNewsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBJDNewsDaoConfig = daoConfigMap.get(DBJDNewsDao.class).clone();
        dBJDNewsDaoConfig.initIdentityScope(type);

        dBZHNewsDaoConfig = daoConfigMap.get(DBZHNewsDao.class).clone();
        dBZHNewsDaoConfig.initIdentityScope(type);

        dBJDNewsDao = new DBJDNewsDao(dBJDNewsDaoConfig, this);
        dBZHNewsDao = new DBZHNewsDao(dBZHNewsDaoConfig, this);

        registerDao(DBJDNews.class, dBJDNewsDao);
        registerDao(DBZHNews.class, dBZHNewsDao);
    }
    
    public void clear() {
        dBJDNewsDaoConfig.clearIdentityScope();
        dBZHNewsDaoConfig.clearIdentityScope();
    }

    public DBJDNewsDao getDBJDNewsDao() {
        return dBJDNewsDao;
    }

    public DBZHNewsDao getDBZHNewsDao() {
        return dBZHNewsDao;
    }

}
